name: Deploy to vercel on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - uses: actions/checkout@v4
      - uses: dkershner6/vercel-set-env-action@v1
        with:
          token: ${{ secrets.VERCEL_TOKEN }}
          projectName: arxiv-fe
          envVariableKeys: NEXT_PUBLIC_SUPABASE_URL,NEXT_PUBLIC_SUPABASE_ANON_KEY,GEMINI_API_KEY,METABASE_URL,METABASE_USERNAME,METABASE_PASSWORD
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          TARGET_NEXT_PUBLIC_SUPABASE_URL: preview,development,production
          TYPE_NEXT_PUBLIC_SUPABASE_URL: encrypted

          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          TARGET_NEXT_PUBLIC_SUPABASE_ANON_KEY: preview,development,production
          TYPE_NEXT_PUBLIC_SUPABASE_ANON_KEY: encrypted

          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          TARGET_GEMINI_API_KEY: preview,development,production
          TYPE_GEMINI_API_KEY: encrypted

          METABASE_URL: ${{ secrets.METABASE_URL }}
          TARGET_METABASE_URL: preview,development,production
          TYPE_METABASE_URL: encrypted

          METABASE_USERNAME: ${{ secrets.METABASE_USERNAME }}
          TARGET_METABASE_USERNAME: preview,development,production
          TYPE_METABASE_USERNAME: encrypted

          METABASE_PASSWORD: ${{ secrets.METABASE_PASSWORD }}
          TARGET_METABASE_PASSWORD: preview,development,production
          TYPE_METABASE_PASSWORD: encrypted

      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-args: "--prod"
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
